services:
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - '7700:7700'
    volumes:
      - ./meili_data:/meili_data
    environment:
      MEILI_MASTER_KEY: 'masterKey'